"""
	Houses a dictionary holding references to every commandavailable
	This file is generated by scripts/update_all_commands.py
"""
from .alias_command import AliasCommand
from .command_line_commands import CowSayCommand
from .command_line_commands import FortuneCommand
from .dankmemes_command import DankMemesCommand
from .help_command import HelpCommand
from .replace_command import ReplaceCommand
from .sports_commands import NBACommand
from .sports_commands import NCAAMCommand
from .spotify_commands import SpotifySearchCommand


commands = {
    '!replace': ReplaceCommand,
    '!ncaam': NCAAMCommand,
    '!fortune': FortuneCommand,
    '!nba': NBACommand,
    '!dankmemes': DankMemesCommand,
    '!song': SpotifySearchCommand,
    '!cowsay': CowSayCommand,
    '!help': HelpCommand,
    '!alias': AliasCommand,
}
