"""
	Houses a dictionary holding references to every commandavailable
	This file is generated by scripts/update_all_commands.py
"""
from .sports_commands import NCAAMCommand
from .sports_commands import NBACommand
from .dankmemes_command import DankMemesCommand
from .spotify_commands import SpotifySearchCommand
from .butts_command import ButtCommand
from .command_line_commands import CowSayCommand
from .command_line_commands import FortuneCommand
from .help_command import HelpCommand
from .alias_command import AliasCommand


commands = {
    '!ncaam': NCAAMCommand,
    '!alias': AliasCommand,
    '!help': HelpCommand,
    '!cowsay': CowSayCommand,
    '!butt': ButtCommand,
    '!nba': NBACommand,
    '!fortune': FortuneCommand,
    '!dankmemes': DankMemesCommand,
    '!song': SpotifySearchCommand,
}
