"""
	Houses a dictionary holding references to every commandavailable
	This file is generated by scripts/update_all_commands.py
"""
from .sports_commands import NCAAMCommand
from .sports_commands import NBACommand
from .cowsay_command import CowSayCommand
from .dankmemes_command import DankMemesCommand
from .spotify_commands import SpotifySearchCommand
from .butts_command import ButtCommand
from .help_command import HelpCommand


commands = {
	'!help': HelpCommand,
	'!ncaam': NCAAMCommand,
	'!dankmemes': DankMemesCommand,
	'!cowsay': CowSayCommand,
	'!song': SpotifySearchCommand,
	'!butt': ButtCommand,
	'!nba': NBACommand,
}
